# Generated by Django 4.0.3 on 2022-04-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profilr',
            new_name='Profile',
        ),
    ]
